name: ngcm
dependencies:
- appnope=0.1.0
- backports=1.0
- bokeh=0.11.1
- ca-certificates=2016.2.28
- cloudpickle=0.2.1
- cycler=0.10.0
- dask=0.9.0
- decorator=4.0.9
- entrypoints=0.2.1
- freetype=2.6.3
- get_terminal_size=1.0.0
- ipykernel=4.3.1
- ipython=4.2.0
- ipython_genutils=0.1.0
- ipywidgets=5.1.5
- jinja2=2.8
- jsonschema=2.5.1
- jupyter_client=4.2.2
- jupyter_core=4.1.0
- libpng=1.6.21
- locket=0.2.0
- markupsafe=0.23
- matplotlib=1.5.1
- mistune=0.7.2
- mkl=11.3.3
- nbconvert=4.2.0
- nbformat=4.0.1
- notebook=4.2.0
- numpy=1.11.0
- openssl=1.0.2h
- pandas=0.18.1
- partd=0.3.3
- pexpect=4.1.0
- pickleshare=0.7.2
- pip=8.1.1
- ptyprocess=0.5.1
- pygments=2.1.3
- pyparsing=2.1.4
- python=3.4
- python-dateutil=2.5.3
- python.app=1.2
- pytz=2016.4
- pyyaml=3.11
- pyzmq=15.2.0
- readline=6.2
- requests=2.10.0
- scikit-learn=0.17.1
- scipy=0.17.1
- seaborn=0.7.0
- setuptools=21.2.1
- simplegeneric=0.8.1
- six=1.10.0
- sqlite=3.9.2
- terminado=0.6
- tk=8.5.19
- toolz=0.7.4
- tornado=4.3
- traitlets=4.2.1
- wheel=0.29.0
- widgetsnbextension=1.2.3
- xz=5.0.5
- yaml=0.1.6
- zlib=1.2.8
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0

